version: '3.8'

services:
  # Основное приложение Пушкин
  pushkin:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis_db
      - SECRET_KEY=YOUR_SUPER_SECRET_KEY_HERE
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis_db
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  # База данных и брокер сообщений
  redis_db:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  # Экспортер метрик Redis для Prometheus
  redis_exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis_db:6379
    command: ["--check-keys", "pushkin:metrics:*"]
    ports:
      - "9121:9121"
    depends_on:
      - redis_db

  # Сборщик метрик
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Визуализация (Мониторинг)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana # Данные будут жить тут
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # Эмулятор сетевого устройства (Mock Switch)
  # Чтобы запустить 10 штук, используй: docker-compose up -d --scale mock_switch=10
  mock_switch:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "2222-2232:22"
    environment:
      - PYTHONUNBUFFERED=1
    # Порт 22 открыт только внутри сети Docker для Пушкина
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
        
  mock_telnet:
    build:
      context: .
      dockerfile: Dockerfile.mock.telnet
    ports:
      - "2233-2243:23"

  mock_telnet2:
    build:
      context: .
      dockerfile: Dockerfile.mock.telnet2
    ports:
      - "2244-2254:23"

volumes:
  grafana_data: # Объявляем именованный том
